twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      teleop_keyboard:
        topic   : cmd_vel_sal
        timeout : 0.5
        priority: 100
      tracker:
        topic   : cmd_vel_tracker
        timeout : 0.5
        priority: 10

      